/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.JogoController;
import controller.SelecaoController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Jogador;
import model.Selecao;

/**
 *
 * @author Samsung
 */
public class Jogo extends javax.swing.JPanel {

    /**
     * Creates new form Jogo
     */
    public Jogo(TelaInicial telaInicial) {
        initComponents();
        this.telaInicial = telaInicial;
        
        jogadoresBtn = new JButton[] {
            jogador1,
            jogador2,
            jogador3,
            jogador4,
            jogador5,
            jogador6,
            jogador7,
            jogador8,
            jogador9,
            jogador10,
            jogador11,
            jogador11,
            jogador12,
            jogador13,
            jogador14,
            jogador15,
            jogador16,
            jogador17,
            jogador18,
            jogador19,
            jogador20,
            jogador21,
            jogador22,
            jogador23
        };
        carregaJogadores();
    }

    public void carregaJogadores() {
      Selecao selecao = jogoCtl.sortearSelecao();
      
      selecaoLabel.setText(selecao.getPais() + " - " + selecao.getAno());
      int i = 0;
      for(Jogador jogador : selecao.getEscalacao()) {
          jogadoresBtn[i].setText(jogador.getNome());
          jogadoresBtn[i++].setName(jogador.getNome() + "_" + jogador.getOverall() + "_"  + jogador.getPosicao());
      }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        sorteio = new javax.swing.JPanel();
        selecaoLabel = new javax.swing.JLabel();
        jogadores = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jogador1 = new javax.swing.JButton();
        jogador2 = new javax.swing.JButton();
        jogador3 = new javax.swing.JButton();
        jogador4 = new javax.swing.JButton();
        jogador5 = new javax.swing.JButton();
        jogador6 = new javax.swing.JButton();
        jogador7 = new javax.swing.JButton();
        jogador8 = new javax.swing.JButton();
        jogador9 = new javax.swing.JButton();
        jogador10 = new javax.swing.JButton();
        jogador11 = new javax.swing.JButton();
        jogador12 = new javax.swing.JButton();
        jogador13 = new javax.swing.JButton();
        jogador14 = new javax.swing.JButton();
        jogador15 = new javax.swing.JButton();
        jogador16 = new javax.swing.JButton();
        jogador17 = new javax.swing.JButton();
        jogador18 = new javax.swing.JButton();
        jogador19 = new javax.swing.JButton();
        jogador20 = new javax.swing.JButton();
        jogador21 = new javax.swing.JButton();
        jogador22 = new javax.swing.JButton();
        jogador23 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtSelecaoJogador = new javax.swing.JLabel();
        campo = new javax.swing.JPanel();
        ca = new javax.swing.JLabel();
        pd = new javax.swing.JLabel();
        pe = new javax.swing.JLabel();
        mc = new javax.swing.JLabel();
        mei = new javax.swing.JLabel();
        vol = new javax.swing.JLabel();
        ld = new javax.swing.JLabel();
        le = new javax.swing.JLabel();
        zag2 = new javax.swing.JLabel();
        zag1 = new javax.swing.JLabel();
        gol = new javax.swing.JLabel();

        sorteio.setBackground(new java.awt.Color(204, 255, 153));

        selecaoLabel.setText("Brasil");

        jogadores.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jogador1.setText("jogador 1");
        jogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador2.setText("jogador 2");
        jogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador3.setText("jogador 3");
        jogador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador4.setText("jogador 4");
        jogador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador5.setText("jogador 5");
        jogador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador6.setText("jogador 6");
        jogador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador7.setText("jogador 7");
        jogador7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador8.setText("jogador 8");
        jogador8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador9.setText("jogador 9");
        jogador9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador10.setText("jogador 10");
        jogador10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador11.setText("jogador 11");
        jogador11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador12.setText("jogador 11");
        jogador12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador13.setText("jogador 11");
        jogador13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador14.setText("jogador 11");
        jogador14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador15.setText("jogador 11");
        jogador15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador16.setText("jogador 11");
        jogador16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador17.setText("jogador 11");
        jogador17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador18.setText("jogador 11");
        jogador18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador19.setText("jogador 11");
        jogador19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador20.setText("jogador 11");
        jogador20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador21.setText("jogador 11");
        jogador21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador22.setText("jogador 11");
        jogador22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        jogador23.setText("jogador 11");
        jogador23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorSelecionado(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogador1)
                    .addComponent(jogador2)
                    .addComponent(jogador3)
                    .addComponent(jogador4)
                    .addComponent(jogador5)
                    .addComponent(jogador6)
                    .addComponent(jogador7)
                    .addComponent(jogador8)
                    .addComponent(jogador9)
                    .addComponent(jogador10)
                    .addComponent(jogador11)
                    .addComponent(jogador12)
                    .addComponent(jogador13)
                    .addComponent(jogador14)
                    .addComponent(jogador15)
                    .addComponent(jogador16)
                    .addComponent(jogador17)
                    .addComponent(jogador18)
                    .addComponent(jogador19)
                    .addComponent(jogador20)
                    .addComponent(jogador21)
                    .addComponent(jogador22)
                    .addComponent(jogador23))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jogador1, jogador10, jogador11, jogador2, jogador3, jogador4, jogador5, jogador6, jogador7, jogador8, jogador9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jogador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogador23)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jogadores.setViewportView(jPanel1);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtSelecaoJogador.setText("Selecione o jogador desejado!");

        javax.swing.GroupLayout sorteioLayout = new javax.swing.GroupLayout(sorteio);
        sorteio.setLayout(sorteioLayout);
        sorteioLayout.setHorizontalGroup(
            sorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(sorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSelecaoJogador)
                    .addComponent(btnVoltar)
                    .addComponent(selecaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sorteioLayout.setVerticalGroup(
            sorteioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSelecaoJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        campo.setBackground(new java.awt.Color(0, 204, 204));

        ca.setText("CA");

        pd.setText("PD");

        pe.setText("PE");

        mc.setText("MC");

        mei.setText("MEI");

        vol.setText("VOL");

        ld.setText("LD");

        le.setText("LE");

        zag2.setText("ZAG");

        zag1.setText("ZAG");

        gol.setText("GOL");

        javax.swing.GroupLayout campoLayout = new javax.swing.GroupLayout(campo);
        campo.setLayout(campoLayout);
        campoLayout.setHorizontalGroup(
            campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoLayout.createSequentialGroup()
                .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(mei)
                        .addGap(85, 85, 85)
                        .addComponent(mc))
                    .addGroup(campoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vol)
                            .addComponent(gol)
                            .addComponent(ca))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(campoLayout.createSequentialGroup()
                .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(le)
                        .addGap(47, 47, 47)
                        .addComponent(zag1)
                        .addGap(45, 45, 45)
                        .addComponent(zag2)
                        .addGap(39, 39, 39)
                        .addComponent(ld))
                    .addGroup(campoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pe)
                        .addGap(132, 132, 132)
                        .addComponent(pd)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        campoLayout.setVerticalGroup(
            campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(ca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pe)
                    .addComponent(pd))
                .addGap(32, 32, 32)
                .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mei)
                    .addComponent(mc))
                .addGap(19, 19, 19)
                .addComponent(vol)
                .addGap(18, 18, 18)
                .addGroup(campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le)
                    .addComponent(zag1)
                    .addComponent(zag2)
                    .addComponent(ld))
                .addGap(14, 14, 14)
                .addComponent(gol)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jogadorSelecionado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogadorSelecionado
        String[] dados = (((JButton)evt.getSource()).getName()).split("_");
        String nome = dados[0];
        int overall = Integer.parseInt(dados[1]);
        String posicao = dados[2];
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja escolher o jogador " + nome + " ?",
                "Confirmacao",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resposta == JOptionPane.YES_OPTION) {
            Jogador jogador = new Jogador(nome, overall, posicao);
            escolhaCtl.adicionarJogador(jogador);
            escolhaCtl.getSelecao();
            carregaJogadores();
        }
    }//GEN-LAST:event_jogadorSelecionado


    private TelaInicial telaInicial;
    private JogoController jogoCtl = new JogoController();
    private SelecaoController escolhaCtl = new SelecaoController();
    private JButton[] jogadoresBtn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel ca;
    private javax.swing.JPanel campo;
    private javax.swing.JLabel gol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jogador1;
    private javax.swing.JButton jogador10;
    private javax.swing.JButton jogador11;
    private javax.swing.JButton jogador12;
    private javax.swing.JButton jogador13;
    private javax.swing.JButton jogador14;
    private javax.swing.JButton jogador15;
    private javax.swing.JButton jogador16;
    private javax.swing.JButton jogador17;
    private javax.swing.JButton jogador18;
    private javax.swing.JButton jogador19;
    private javax.swing.JButton jogador2;
    private javax.swing.JButton jogador20;
    private javax.swing.JButton jogador21;
    private javax.swing.JButton jogador22;
    private javax.swing.JButton jogador23;
    private javax.swing.JButton jogador3;
    private javax.swing.JButton jogador4;
    private javax.swing.JButton jogador5;
    private javax.swing.JButton jogador6;
    private javax.swing.JButton jogador7;
    private javax.swing.JButton jogador8;
    private javax.swing.JButton jogador9;
    private javax.swing.JScrollPane jogadores;
    private javax.swing.JLabel ld;
    private javax.swing.JLabel le;
    private javax.swing.JLabel mc;
    private javax.swing.JLabel mei;
    private javax.swing.JLabel pd;
    private javax.swing.JLabel pe;
    private javax.swing.JLabel selecaoLabel;
    private javax.swing.JPanel sorteio;
    private javax.swing.JLabel txtSelecaoJogador;
    private javax.swing.JLabel vol;
    private javax.swing.JLabel zag1;
    private javax.swing.JLabel zag2;
    // End of variables declaration//GEN-END:variables
}
